@startuml
'https://plantuml.com/class-diagram

interface Startable {
    +void start()
    +void stop()
}

interface ITContainer {
    +String getAbbreviation()
}

interface AdapterContainer {
    +DataSource getTargetDataSource(String serverLists)
}

class GenericContainer

abstract DockerITContainer {
    +void postStart()
}

abstract DockerStorageContainer {
    +void configure()
    +void setCommands()
    +void addEnvs()
    +void mapResources()
    +void postStart()
}

class MySQLContainer {
    StorageContainerConfiguration storageContainerConfiguration
    +void configure()
    +int getPort()
    +Optional<String> getDefaultDatabaseName()
}

class PostgreSQLContainer {
    StorageContainerConfiguration storageContainerConfiguration
    +void configure()
    +int getPort()
    +Optional<String> getDefaultDatabaseName()
}

class OpenGaussContainer {
    StorageContainerConfiguration storageContainerConfiguration
    +void configure()
    +int getPort()
    +Optional<String> getDefaultDatabaseName()
}

Startable <|-- ITContainer
ITContainer <|-- AdapterContainer
GenericContainer <|-- DockerITContainer
ITContainer <|.. DockerITContainer

DockerITContainer <|-- DockerStorageContainer

DockerStorageContainer <|-- MySQLContainer
DockerStorageContainer <|-- PostgreSQLContainer
DockerStorageContainer <|-- OpenGaussContainer

@enduml